spring:
  application:
    name: project
    desc: DevOps Project Service
    version: 4.0
    packageName: com.tencent.devops.project
  datasource:
    url: jdbc:mysql://gamedb.dev.devops.db:10000/devops_project?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: ENC(4thI6E9FBq9rHHDuRXRIyA==)
    password: ENC(muhwM7Fz7zJZF/OsJSlOoA==)

file:
  allowUploadFileTypes: jpg,png,gif,swf,txt,doc,docx,xls,xlsx,ppt,pptx,pdf,flv,rmvb,mp4,svg
  maxUploadFileSize: 52428800

server:
  port: 21912

auth:
  url: http://authapi-dev.open.oa.com

paas_cc:
  url: http://api.apigw-biz.o.oa.com/api/paas-cc/test/project