trigger:
  branches:
    include:
    - master
mr:
  branches:
    include:
    - master

variables:
  name: world

stages:
- stage:
  - job:
      name: Linux Job
      pool:
        container: mirrors.tencent.com/ci/tlinux_ci:latest
      steps:
      - taskType: bash@latest
        displayName: "Step1: Run a multi-line script"
        inputs:
          scriptType: SHELL
          content: |
            #!/bin/bash
            echo "hello ${name}"
      - taskType: bash@latest
        displayName: "Step2: Run a multi-line script"
        inputs:
          scriptType: SHELL
          content: |
            #!/bin/bash
            echo "hello ${name} again"
      - taskType: marketBuild@latest
        displayName: Upload Artifacts
        inputs:
          atomCode: UploadArtifactory
          name: 归档构件
          version: 1.*
          data:
            input:
              filePath: ".ci.yml"
              isCustomize: false
