spring:
  application:
    name: sign
    desc: DevOps Sign Service
    version: 4.0.0
    packageName: com.tencent.devops.sign

server:
  port: 21950

bkci:
  sign:
    tmpDir: "/data/enterprise_sign_tmp/"