spring:
  profiles: prod-gray
  rabbitmq:
    virtual-host: bkdevops
    username: bkdevops
    password: bkdevops
    addresses: 100.97.133.13:5672,100.97.131.7:5672
    listener:
      simple:
        concurrency: 50
    cache:
      channel:
        size: 100

project.gray: true