spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://gamedb.dev.devops.db:10000/devops_artifactory?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: ENC(4thI6E9FBq9rHHDuRXRIyA==)
    password: ENC(muhwM7Fz7zJZF/OsJSlOoA==)
  redis:
    database: 7
    host: redis.v3paas.blueking.db
    password: ENC(24ZS8Y4XnyMzKkKEhsl48q9EPtVVT1AbqJvO/jmDrBI=)
    port: 30003
  rabbitmq:
    virtual-host: soda4_test
    username: soda
    password: soda
    addresses: 100.97.154.15:5672
  cloud:
    consul:
      discovery:
        tags: dev

server:
  port: 80

jfrog:
  url: http://dev.artifactory.oa.com
  username: devops_pipeline_backend_api
  password: ENC(Qvm3Y+sa7vcfW7C9mBpMPf7Y/C+kwkNk+mqsmhqX4xo=)

artifactory:
  outerUrl: https://dev.bkdevops.qq.com/artifactory/download
  thirdPartyUrl: http://dev.gw.open.oa.com

gateway:
  url: dev.gw.open.oa.com
