spring:
  profiles: test
  datasource:
    url: jdbc:mysql://gamedb.test.devops.db:10001/devops_artifactory?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: ENC(Uz/TYMbh1JRiFQzWIlAjUw==)
    password: ENC(L3tk3U/7gjfOxB8Zp6v71w==)
  redis:
    database: 1
    host: ins.build-test.devops.db
    password: ENC(RiqIBF6erMdzvkYmiJAE8w==)
    port: 30000
  cloud:
    consul:
      discovery:
        tags: test
  rabbitmq:
    virtual-host: landun_test
    username: landun
    password: landun
    addresses: 100.97.106.54:5672

server:
  port: 80

jfrog:
  url: http://test.artifactory.oa.com
  username: devops_pipeline_backend_api
  password: ENC(fKA8Key+kcVgBWY7oEgYqoGdLt9ZsydScS2bI/6Cvo4=)

artifactory:
  outerUrl: https://test.bkdevops.qq.com/artifactory/download
  thirdPartyUrl: http://test.gw.open.oa.com

gateway:
  url: test.gw.open.oa.com
