spring:
  profiles: exp
  datasource:
    url: jdbc:mysql://gamedb.dev.devops.db:10000/devops_exp_support?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: ENC(4thI6E9FBq9rHHDuRXRIyA==)
    password: ENC(muhwM7Fz7zJZF/OsJSlOoA==)
  redis:
    database: 0
    host: 9.86.127.192
    password: ENC(FwmBYT8tocKEkkNn/7o7xg==)
    port: 6379
  rabbitmq:
    virtual-host: bkdevops
    username: bkdevops
    password: bkdevops
    addresses: rabbit-server-cluster:5672
  cloud:
    consul:
      discovery:
        tags: exp

server:
  port: 80

jfrog:
  url: http://dev.artifactory.oa.com
  username: devops_pipeline_backend_api
  password: ENC(Qvm3Y+sa7vcfW7C9mBpMPf7Y/C+kwkNk+mqsmhqX4xo=)

artifactory:
  outerUrl: https://exp.bkdevops.qq.com/artifactory/download
  thirdPartyUrl: http://exp.gw.devops.oa.com

gateway:
  url: test.gw.open.oa.com
