spring:
  profiles: dev-gray
  rabbitmq:
    virtual-host: dev-gray
    username: dev-gray
    password: dev-gray
    addresses: 100.97.154.15:5672
  redis:
    database: 8
    host: redis.v3paas.blueking.db
    password: ENC(24ZS8Y4XnyMzKkKEhsl48q9EPtVVT1AbqJvO/jmDrBI=)
    port: 30003



auth:
  idProvider: client
  grantType: client_credentials
  stagingEnvName: staging
  testEnvName: test
  prodEnvName: prod
  stagingUrl: http://authapi-dev.open.oa.com
  testUrl: http://authapi-test.open.oa.com
  prodUrl: http://authapi.open.oa.com
  url: http://authapi-dev.open.oa.com

cc:
  testUrl: http://api.apigw-biz.o.oa.com/api/paas-cc/test
  prodUrl: http://api.apigw-biz.o.oa.com/api/paas-cc/prod

enc:
  key: rAFOey00bcuMNMrt

project:
  gray: true

devopsGateway:
  build: http://dev.devgw.devops.oa.com
  host: http://dev.devops.oa.com
  api: http://dev.api.devops.oa.com
  outer: https://dev.bkdevops.qq.com
  outerApi: https://dev-api.bkdevops.qq.com

