spring:
  application:
    name: project
    desc: DevOps Project Service
    version: 4.0
    packageName: com.tencent.devops.project

server:
  port: 21912

paas_cc:
  url: http://api.apigw-biz.o.oa.com/api/paas-cc/test/project