server:
  port: 8080
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///Users/rdeng/work/codes/devops-config
          search-paths:
            - config-server
            - "config-server/{application}"
          default-label: dev-gray
    consul:
      discovery:
        tags: dev

---
spring:
  profiles: dev-gray
  cloud:
    config:
      server:
        git:
          uri: file:///data1/work/config/devops-config

---
spring:
  profiles: prod
  cloud:
    config:
      server:
        git:
          uri: file:///data/bkci/config-server/devops-config
          default-label: master
    consul:
      discovery:
        tags: prod

server:
  port: 21937

---
spring:
  profiles: prod-gray