spring:
  application:
    name: lambda
    desc: Devops Lambda Service
    version: 4.0
    packageName: com.tencent.devops.lambda
  datasource:
    url: jdbc:mysql://10.125.48.80:3306/devops_lambda?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: tig4php
    password: tig4php
  redis:
    database: 2
    host: 10.125.48.80
    password: itdev@db
  rabbitmq:
    virtual-host: soda4
    username: soda
    password: soda
    addresses: 10.125.48.80:5672
  cloud:
    consul:
      discovery:
        tags: local
  kafka:
    producer:
      bootstrap-servers: tendata-public.sz.kafka.db.:32276
      batch-size: 16384
      retries: 3
      acks: 1
    listener:
      concurrency: 3

server:
  port: 8001

kafkaJaasConfig:
  userName: tendata-bkdevops-296
  password: WGQPd5y1gq9zEYQ9

elasticsearch:
  ip: bk-test5614.sh.es.db
  port: 9300
  cluster: bk-test5614
  keystore:
    filePath: /data/certificate/CN=sgadmin-keystore.jks
    password: de9aee7c83910d86cb2a
  truststore:
    filePath: /data/certificate/truststore.jks
    password: b79d1f43876458cb6c2f