#####################################################################################################################
# 项目ID: bkdevops 
# 流水线ID: p-5ef04bbb79dd42a9941c9e535d81eeb7 
# 流水线名称: BK-CI后端MR代码检查 
# 导出时间: 2021-08-10 18:52:08 
# 
# 注意：不支持系统凭证(用户名、密码)的导出，请检查系统凭证的完整性！ 
# 注意：[插件]输入参数可能存在敏感信息，请仔细检查，谨慎分享！！！ 
# 注意：[插件]工蜂CI不支持蓝盾老版本的插件，请在研发商店搜索新插件替换 
#####################################################################################################################

---
version: "v2.0"
name: "Backend"
on:
  mr: [ integration ]

stages:
- name: "PreMR"
  label:
  - "Build"
  jobs:
    job_1:
      name: "Build"
      runs-on: docker
      steps:
      - checkout: self
      - uses: mysqlservice@1.*
        id: mysqlservice
        name: Start MySQL
        with:
          imageName: mysql:5.7
          port: 3306
          mysqlPw: root
          initCmd: SELECT NOW();
      - name: "init MySQL"
        run: |
          set -x
          cd support-files/sql
          for i in *.sql; do 
            echo $i;mysql -h ${{steps.mysqlservice.outputs.MYSQL_IP}} -P ${{steps.mysqlservice.outputs.MYSQL_PORT}} -uroot -proot < $i
          done
      - name: "Gradle Build"
        env:
          mysqlURL: "${{steps.mysqlservice.outputs.MYSQL_IP}}:${{steps.mysqlservice.outputs.MYSQL_PORT}}"
          mysqlUser: root
          mysqlPasswd: root
        run: | 
          cd src/backend/ci/ext/tencent
          ../../gradlew -DmysqlURL=$mysqlURL -DmysqlUser=$mysqlUser -DmysqlPasswd=$mysqlPasswd  -DenvironmentMysqlURL=$mysqlURL -DenvironmentMysqlUser=$mysqlUser -DenvironmentMysqlPasswd=$mysqlPasswd -DprojectMysqlURL=$mysqlURL -DprojectMysqlUser=$mysqlUser -DprojectMysqlPasswd=$mysqlPasswd -DmysqlPrefix=devops_ test classes

