version: "v2.0"
name: "Backend"
on:
  mr: [ integration ]

stages:
- name: "PreMR"
  label:
  - "Build"
  jobs:
    job_1:
      name: "Build"
      runs-on: docker
      steps:
      - checkout: self
      - uses: mysqlservice@1.*
        id: mysqlservice
        name: Start MySQL
        with:
          imageName: mysql:5.7
          port: 3306
          mysqlPw: root
          initCmd: select version();

      - name: "init MySQL"
        run: |
          set -x
          cd support-files/sql/tencent
          for i in *.sql; do
            echo $i;mysql -h ${{steps.mysqlservice.outputs.MYSQL_IP}} -P ${{steps.mysqlservice.outputs.MYSQL_PORT}} -uroot -proot < $i
          done
          mysql -h ${{steps.mysqlservice.outputs.MYSQL_IP}} -P ${{steps.mysqlservice.outputs.MYSQL_PORT}} -uroot -proot -e "use devops_ci_artifactory; show tables;"

      - name: "Gradle Build"
        env:
          mysqlURL: "${{steps.mysqlservice.outputs.MYSQL_IP}}:${{steps.mysqlservice.outputs.MYSQL_PORT}}"
          mysqlUser: root
          mysqlPasswd: root
        run: | 
          cd src/backend/ci/ext/tencent
          ../../gradlew -DmysqlURL=$mysqlURL -DmysqlUser=$mysqlUser -DmysqlPasswd=$mysqlPasswd  -DenvironmentMysqlURL=$mysqlURL -DenvironmentMysqlUser=$mysqlUser -DenvironmentMysqlPasswd=$mysqlPasswd -DprojectMysqlURL=$mysqlURL -DprojectMysqlUser=$mysqlUser -DprojectMysqlPasswd=$mysqlPasswd -DmysqlPrefix=devops_ci_ test classes

