version: "v2.0"
name: "前端部署Test"
variables:
  modules: "nav,pipeline,vs,ticket,codelib,quality,turbo,atomstore,artifactory,environment,experience,stream"
  ips: "11.185.145.49"
  # 9.134.78.69,10.123.135.151,9.66.32.218

on:
  schedules:
    cron: 0 * * * *
    branches: [ "test" ]

stages:
- name: "Build"
  label:
  - "Build"
  jobs:
    job_1:
      name: "构建环境-LINUX"
      runs-on: docker
      steps:
      - checkout: "http://git.code.oa.com/bkdevops/bk-ci.git"
        name: Checkout
        with:
          refName: test
      - name: "拉取前端占位符"
        checkout: "http://git.code.oa.com/bkdevops/devops-config.git"
        with:
          pullType: "BRANCH"
          refName: "integration"
          localPath: "devops-config"
      - uses: calculatehash@1.*
        id: calculate
        with:
          file_path: src/frontend/package.json
            # src/frontend/devops-nav/package.json
            # src/frontend/devops-pipeline/package.json
            # src/frontend/devops-atomstore/package.json
            # src/frontend/devops-codelib/package.json
            # src/frontend/devops-environment/package.json
            # src/frontend/devops-quality/package.json
            # src/frontend/devops-experience/package.json
            # src/frontend/devops-turbo/package.json
          calculate_func: md5
      - uses: cache@1.*
        id: cache
        with:
          cacheKey: "bk_ci_frontend_test_linux_${{ steps.calculate.outputs.hash_value }}"
          cachePaths: |
            src/frontend/node_modules
            src/frontend/devops-nav/node_modules
            src/frontend/devops-pipeline/node_modules
            src/frontend/devops-atomstore/node_modules
            src/frontend/devops-codelib/node_modules
            src/frontend/devops-environment/node_modules
            src/frontend/devops-quality/node_modules
            src/frontend/devops-experience/node_modules
            src/frontend/devops-turbo/node_modules
          restoreKeys: "bk_ci_frontend_test_linux_"
      - run: |
          cd src/frontend
          if [ ${{ steps.cache.outputs.cacheHit }} == 'false' ]
          then
            yarn
          else
            echo "package.json has not changed"
          fi
          ls -l ./node_modules/.bin
          chmod -R 777 ./node_modules
          yarn public -e test -l v2 -t tencent

          cd ./frontend/ || exit 1

          cp -rf ${WORKSPACE}/devops-config/gateway_frontend/* ${WORKSPACE}/
          rm -r ${WORKSPACE}/ci || echo "no ci director"
          mkdir -p ${WORKSPACE}/ci/frontend

          cp -r ./* ${WORKSPACE}/ci/frontend/
          cp ./console/frontend#console#index.html ${WORKSPACE}/support-files/templates/ || echo "no console module"
          cp ./pipeline/frontend#pipeline#index.html ${WORKSPACE}/support-files/templates/ || echo "no pipeline module"

          cd ${WORKSPACE}/scripts/
          cp -rf ci_env_test.properties ci_env.properties
          sh ./render_ci -m ci ../support-files/templates/*

          cd ${WORKSPACE}/ci/frontend/
          zip -r frontend.zip ./* && cp frontend.zip ${WORKSPACE}
      - name: "Upload"
        uses: "UploadArtifactory@1.*"
        with:
          filePath: "frontend.zip"
- name: "Deploy"
  label:
  - "Deploy"
  jobs:
    job_2:
      name: "无编译环境"
      runs-on: agentless
      steps:
      - name: "分发"
        uses: "jobFileTransferForOA@1.*"
        with:
          bizId: "100205"
          srcType: "PIPELINE"
          srcPath: "frontend.zip"
          targetIpList: ${{ variables.ips }}
          targetAccount: "root"
          targetPath: "/data/tmp"
      - name: "发布"
        uses: "jobExecuteScriptForOA@1.*"
        with:
          bizId: "100205"
          scriptType: "1"
          scriptContent: |
            cd /data/tmp
            rm -rf frontend
            mkdir -p frontend
            unzip -o frontend.zip -d frontend
            mkdir -p /data/bkee/ci/frontend
            mkdir -p /data/bkee/ci/frontend-gray
            cp -rf /data/tmp/frontend/* /data/bkee/ci/frontend
            cp -rf /data/tmp/frontend/* /data/bkee/ci/frontend-gray

          account: "root"
          targetIpList: ${{ variables.ips }}

notices:
- type: wework-message

