version: "v2.0"
name: "bk-ci前端部署【Dev】"
variables:
  modules: "nav,pipeline,vs,ticket,codelib,quality,turbo,atomstore,artifactory,environment,experience,stream"
  branch: "frontend-develop"
  path: "default"
  ips: "11.185.144.156,9.4.20.15"

on:
  push: ["frontend-develop"]
  schedules:
    cron: 0 * * * *
    branches: [ "frontend-develop" ]

stages:
- name: "Build"
  label:
  - "Build"
  jobs:
    job_1:
      name: "构建环境-LINUX"
      runs-on: docker
      steps:
      - checkout: self
      - name: "拉取前端占位符"
        with:
          pullType: "BRANCH"
          branchName: "integration"
          localPath: "devops-config"
        checkout: "http://git.code.oa.com/bkdevops/devops-config.git"
      - uses: calculatehash@1.*
        id: calculate
        with:
          file_path: src/frontend/package.json
          calculate_func: md5
      - uses: cache@1.*
        id: cache
        with:
          cacheKey: "bk_ci_frontend_dev_linux_${{ steps.calculate.outputs.hash_value }}"
          cachePaths: "src/frontend/node_modules"
          restoreKeys: "bk_ci_frontend_dev_linux_"
      - name: "Bash"
        run: |
          cd src/frontend
          if [ ${{ steps.cache.outputs.cacheHit }} == 'false' ]
          then
            yarn
          else
            echo "package.json has not changed"
          fi
          yarn public -e dev -t tencent -s ${{ variables.modules }}

          cd ./frontend/ || exit 1

          cp -rf ${{ ci.workspace }}/devops-config/gateway_frontend/* ${{ ci.workspace }}/
          rm -r ${{ ci.workspace }}/ci || echo "no ci director"
          mkdir -p ${{ ci.workspace }}/ci/frontend

          cp -r ./* ${{ ci.workspace }}/ci/frontend/
          cp ./console/frontend#console#index.html ${{ ci.workspace }}/support-files/templates/ || echo "no console module"
          cp ./pipeline/frontend#pipeline#index.html ${{ ci.workspace }}/support-files/templates/ || echo "no pipeline module"

          cd ${{ ci.workspace }}/scripts/
          cp -rf ci_env_dev.properties ci_env.properties
          sh ./render_ci -m ci ../support-files/templates/*

          cd ${{ ci.workspace }}/ci/frontend/
          zip -r frontend.zip ./* && cp frontend.zip ${{ ci.workspace }}
      - name: "Upload"
        uses: "UploadArtifactory@1.*"
        with:
          filePath: "frontend.zip"
          # repoName: "pipeline"
- name: "Deploy"
  label:
  - "Deploy"
  jobs:
    job_2:
      name: "无编译环境"
      runs-on: agentless
      steps:
      - name: "分发"
        uses: "jobFileTransferForOA@1.*"
        with:
          bizId: "100205"
          srcType: "PIPELINE"
          srcPath: "frontend.zip"
          targetIpList: ${{ variables.ips }}
          targetAccount: "root"
          targetPath: "/data/tmp"
      - name: "发布"
        uses: "jobExecuteScriptForOA@1.*"
        with:
          bizId: "100205"
          scriptType: "1"
          scriptContent: |
            cd /data/tmp
            rm -rf frontend
            mkdir -p frontend
            unzip -o frontend.zip -d frontend

            if [ "${{ variables.path }}" = "default" ]; then
                f_path=frontend
            else
                f_path=frontend-${{ variables.path }}
            fi

            mkdir -p /data/bkee/ci/$f_path
            cp -rf /data/tmp/frontend/* /data/bkee/ci/$f_path

          account: "root"
          targetIpList: ${{ variables.ips }}

notices:
- type: wework-message