version: "v2.0"
name: "前端部署Test"
variables:
  modules: "nav,pipeline,vs,ticket,codelib,quality,turbo,atomstore,artifactory,environment,experience,stream"
  ips: "11.185.145.49"
  # 9.134.78.69,10.123.135.151,9.66.32.218

on:
  push: ["test"]

stages:
- name: "Build"
  label:
  - "Build"
  jobs:
    job_1:
      name: "构建环境-LINUX"
      runs-on: docker
      steps:
      - checkout: self
      - name: "拉取前端占位符"
        with:
          pullType: "BRANCH"
          branchName: "integration"
          localPath: "devops-config"
        checkout: "http://git.code.oa.com/bkdevops/devops-config.git"
      - name: "Bash"
        run: |
          cd src/frontend
          npm install -g lerna
          yarn start
          yarn public -e dev -t tencent -s ${{ variables.modules }}

          cd ./frontend/ || exit 1

          cp -rf ${{ ci.workspace }}/devops-config/gateway_frontend/* ${{ ci.workspace }}/
          rm -r ${{ ci.workspace }}/ci || echo "no ci director"
          mkdir -p ${{ ci.workspace }}/ci/frontend

          cp -r ./* ${{ ci.workspace }}/ci/frontend/
          cp ./console/frontend#console#index.html ${{ ci.workspace }}/support-files/templates/ || echo "no console module"
          cp ./pipeline/frontend#pipeline#index.html ${{ ci.workspace }}/support-files/templates/ || echo "no pipeline module"

          cd ${{ ci.workspace }}/scripts/
          cp -rf ci_env_dev.properties ci_env.properties
          sh ./render_ci -m ci ../support-files/templates/*

          cd ${{ ci.workspace }}/ci/frontend/
          zip -r frontend.zip ./* && cp frontend.zip ${{ ci.workspace }}
      - name: "Upload"
        uses: "UploadArtifactory@1.*"
        with:
          filePath: "frontend.zip"
- name: "Deploy"
  label:
  - "Deploy"
  jobs:
    job_2:
      name: "无编译环境"
      runs-on: agentless
      steps:
      - name: "分发"
        uses: "jobFileTransferForOA@1.*"
        with:
          bizId: "100205"
          srcType: "PIPELINE"
          srcPath: "frontend.zip"
          targetIpList: ${{ variables.ips }}
          targetAccount: "root"
          targetPath: "/data/tmp"
      - name: "发布"
        uses: "jobExecuteScriptForOA@1.*"
        with:
          bizId: "100205"
          scriptType: "1"
          scriptContent: |
            cd /data/tmp
            rm -rf frontend
            mkdir -p frontend
            unzip -o frontend.zip -d frontend
            mkdir -p /data/bkee/ci/frontend
            mkdir -p /data/bkee/ci/frontend-gray
            cp -rf /data/tmp/frontend/* /data/bkee/ci/frontend
            cp -rf /data/tmp/frontend/* /data/bkee/ci/frontend-gray

          account: "root"
          targetIpList: ${{ variables.ips }}

notices:
- type: wework-message

