# Common config Template 重复的通用的配置抽离在到

spring:
  application:
    version: 4.0.0
# consul config do not need to change
  cloud:
    consul:
      port: __DEVOPS_CONSUL_PORT__
      discovery:
        tags: __DEVOPS_CONSUL_TAG__
# redis config
  redis:
#   # Redis sentinel 集群方式配置
#    sentinel:
#      master: __REDIS_MASTER_NAME__
#      nodes: __REDIS_CLUSTER_HOST__:__REDIS_CLUSTER_PORT__
#   # Redis 单机配置方式
    host: __REDIS_IP0__
    port: __REDIS_PORT__
    password: __REDIS_PASS__
    database: __REDIS_DB__
    pool:
      max-active: 16
      max-wait:  2000
# rabbitmq config
  rabbitmq:
    virtual-host: __RABBITMQ_VHOST__
    username: __RABBITMQ_USERNAME__
    password: __RABBITMQ_PASSWORD__
    addresses: __RABBITMQ_HOST__:__RABBITMQ_PORT__

# http concurrency
server:
  undertow:
    worker-threads: 100

# gateway for system
devopsGateway:
  build: http://__DEVOPS_FQDN__:__DEVOPS_HTTP_PORT__        # for build agent like dev.devops.blueking.com:80
  host: http://__DEVOPS_FQDN__:__DEVOPS_HTTP_PORT__         # for web many be same to buildGateWay
  api: http://__DEVOPS_FQDN__:__DEVOPS_HTTP_PORT__          # for api many be same to host
  outer: http://__DEVOPS_FQDN__:__DEVOPS_HTTP_PORT__        # for internet domain
  outerApi: http://__DEVOPS_FQDN__:__DEVOPS_HTTP_PORT__        # for internet domain

auth:
  idProvider: client
  grantType: client_credentials
  stagingEnvName: staging
  testEnvName: test
  prodEnvName: prod
  stagingUrl: http://authapi-dev.open.oa.com
  testUrl: http://authapi-test.open.oa.com
  prodUrl: http://authapi.open.oa.com
  bcsSecret: YH777kfUgQgpzisfte1S700S5q2N2FFQhtfFGwhQeO3E7TIs6v
  codeSecret: xI7DbH5tuOPkYDeaD6zGmEMhagnExV3loRooP0wDmbcfda4m7S
  pipelineSecret: I6ua62oGX8HocKNOpCtjrEiebQv5X5sF4jAYfvwMpYZsR6F4Qm
  artifactorySecret: DSudQR9g9a32xKExVbGgMJA1itJGXltQVS08D6tCt7kwrDzMpp
  ticketSecret: bBEHPz9YoEK1domD7mxPbiQIzw54j9Q1XRZFhSAztXE4I3G1MC
  environmentSecret: t51LIa27rBa4NMGQbydEg4mg6jU26g74WUuRPG4MpkKq9LTWqW
  experienceSecret: 9enfUAZtdgmMHAVUSnBvbXRDES4xFzvitMpV3IdrzcMDbu42UT
  vsSecret: 47591GshxBNnjiH1Nix4HcAR6xEdgwvYfVuNjN7G9eqrN6BQay
  qualitySecret: b3Z15sIjCmEmtRdP9HDuxv4r1mGaEzc9Ks23KHy9QQCTJGUKss
  wetestSecret: rtZWjB8sGEW1kIHmTLgeHRjACe1FPw5SKb8V9VjQ89kNM8AAVH

cc:
  testUrl: http://api.apigw-biz.o.oa.com/api/paas-cc/test
  prodUrl: http://api.apigw-biz.o.oa.com/api/paas-cc/prod
