spring:
  application:
    name: defect
    desc: Defect Service
    version: 4.0.0
    packageName: com.tencent.bk.codecc.defect
  redis:
    host: 10.125.224.234132415
    port: 637951452
    password: CodeCC_1024@1teafadg6
  rabbitmq:
    virtual-host: codecc_dev
    username: codecc
    password: codecc
    addresses: 10.123.102.174:5672
  cloud:
    consul:
      discovery:
        tags: local
  data:
    mongodb:
      uri: mongodb://codecc_ee:codecc1024@10.125.224.233:27017,10.125.224.233:27018,10.125.224.233:27019/db_defect?replicaSet=rs0&slaveOk=true
server:
  port: 8082 # 服务端口


##以下其他环境参数待配置



---


spring:
  profiles : test
#  datasource:
#    url: jdbc:mysql://10.125.48.80:3306/devops_ticket?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#    username: tig4php
#    password: tig4php
  redis:
    database: 2
    host: 10.125.48.80
    password: itdev@db
  rabbitmq:
    virtual-host: codecc_dev
    username: codecc
    password: codecc
    addresses: 10.123.102.174:5672
  cloud:
    consul:
      discovery:
        tags: test
      port: 8080

server:
  port: 8082 # 服务端口


---


spring:
  profiles : prod
#  datasource:
#    url: jdbc:mysql://10.125.48.80:3306/devops_ticket?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#    username: tig4php
#    password: tig4php
  redis:
    database: 2
    host: 10.125.48.80
    password: itdev@db
  rabbitmq:
    virtual-host: codecc_dev
    username: codecc
    password: codecc
    addresses: 10.123.102.174:5672
  cloud:
    consul:
      discovery:
        tags: prod

server:
  port: 8082 # 服务端口