spring:
  application:
    name: monitoring
    desc: DevOps Monitoring Service
    version: 4.0.0
    packageName: com.tencent.devops.monitoring
  rabbitmq:
    virtual-host: bkdevops
    username: guest
    password: guest
    addresses: 127.0.0.1:5672
  datasource:
    url: jdbc:mysql://10.125.48.80:3306/devops_monitoring?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: tig4php
    password: tig4php
  redis:
    database: 2
    host: 10.125.48.80
    password: itdev@db
  cloud:
    consul:
      discovery:
        tags: local

alert:
  users: "johuang"

gateway:
  appCode: bkci
  appSecret: XybK7-.L*(o5lU~N?^)93H3nbV1=l>b,(3jvIAXH!7LolD&Zv<
  uwork:
    sendNocNoticeUrl: http://t.open.oa.com/component/compapi/uwork/noc_notice/

server:
  port: 8085

influxdb:
  server: http://127.0.0.1:8086
  userName: admin
  password: password

bkrepo:
  bkrepoApiUrl: http://dev.bkrepo.oa.com/api/generic
  pkgRepoName: generic-local
  dockerRepoName: docker-local