spring:
  application:
    name: openapi
    desc: SODA Openapi Service
    version: 4.0.0
    packageName: com.tencent.devops.openapi
  rabbitmq:
    virtual-host: soda4
    username: soda
    password: soda
    addresses: 10.125.48.80:5672
  datasource:
    url: jdbc:mysql://10.125.48.80:3306/devops_support?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: tig4php
    password: tig4php
  cloud:
    consul:
      discovery:
        tags: local

server:
  port: 8089


api:
  gateway:
    pub:
      file:
        outer: /data1/work/devops_outer.pub
        inner: /data1/work/devops_inner.pub