spring:
  application:
    name: store
    desc: Landun Support Service
    version: 4.0
    packageName: com.tencent.devops.store
  datasource:
    url: jdbc:mysql://10.125.48.80:3306/devops_store?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: tig4php
    password: tig4php
  redis:
      database: 2
      host: 10.125.48.80
      password: itdev@db
  rabbitmq:
    virtual-host: soda4
    username: soda
    password: soda
    addresses: 10.125.48.80:5672
  cloud:
    consul:
      discovery:
        tags: local

logo:
  allowUploadLogoTypes: jpg,png,svg
  allowUploadLogoWidth: 200
  allowUploadLogoHeight: 200
  maxUploadLogoSize: 2097152

store:
  baseImageDocsLink: /console/store/atomStore/detail/image/
  profileUrlPrefix: http://dayu.oa.com/avatars/
  atomDetailBaseUrl: http://dev.devops.oa.com/console/store/atomStore/detail/atom/
  templateDetailBaseUrl: http://dev.devops.oa.com/console/store/atomStore/detail/template/
  ideAtomDetailBaseUrl: http://dev.devops.oa.com/console/store/atomStore/detail/ide/
  imageDetailBaseUrl: http://dev.devops.oa.com/console/store/atomStore/detail/image/
  moaApproveCallBackUrl: http://dev.api.devops.oa.com/store/api/service/market/approval/moa/callBack
  commentNotifyAdmin: fayewang;carlyin

gateway:
  devnet:
      url: http://dev.devgw.devops.oa.com/
  idc:
      url: http://dev.gw.devops.oa.com/

git:
  plugin:
   nameSpaceId: 105856
  idePlugin:
   nameSpaceId: 127179

aes:
  aesKey: "G/I%yP{?ST}2TXPg"
  aesMock: "******"

pcg:
  image:
    url: http://ciserver.wsd.com/interface?skey=8b116e40-5a06-4d17-a1a8-8a131f1b732d&operator=&interface_name=get_tc_container4web&interface_params= {"from":"landun"}

server:
  port: 8085